apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: azkaban-exe
  namespace: azkaban
spec:
  serviceName: "azkaban-exe"
  selector:
    matchLabels:
      app: azkaban
      deploy: exe
  replicas: 1
  template:
    metadata:
      labels:
        app: azkaban
        deploy: exe
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: azkaban
          image: registry.cn-zhangjiakou.aliyuncs.com/myt-images/azkaban-python3:v3.84.4
          #imagePullPolicy: Always
          #command: ['bash','-c','sleep 1h']
          args: ["exe"]
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - active-exe.sh
                  #- curl "http://`hostname -A|awk '$1=$1'`:12321/executor?action=activate"
            preStop:
              exec:
                command: 
                  #- mysql -u${MYSQL_USER_NAME} -p${MYSQL_USER_PASSWORD} -h${MYSQL_HOST} ${MYSQL_DB} -e "SELECT * FROM executors" 
                  - /bin/bash
                  - -c 
                  - mysql -usuyongjie -pMykj@123456 -hrm-8vb0y96rf7m3fai4m.mysql.zhangbei.rds.aliyuncs.com azkaban -e "UPDATE executors SET active=0 WHERE host='`hostname -A`'"
          env:
            - name: MYSQL_HOST
              value: rm-8vb0y96rf7m3fai4m.mysql.zhangbei.rds.aliyuncs.com
            - name: MYSQL_DB
              value: azkaban
            - name: MYSQL_USER_NAME
              value: suyongjie
            - name: MYSQL_USER_PASSWORD
              value: Mykj@123456
          volumeMounts:
            - name: config
              mountPath: /opt/azkaban/azkaban-web/conf/azkaban.properties
              subPath: azkaban.properties
            - name: tz
              mountPath: /etc/localtime
              subPath: Shanghai
      volumes:
        - name: config
          configMap:
            name: azkaban-exe-config
            items:
              - key: azkaban-exe.properties
                path: azkaban.properties
        - name: tz
          configMap:
            name: tz
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: "intranet"
  name: azkaban-exe
  namespace: azkaban
spec:
  selector:
    app: azkaban
    deploy: exe
  type: LoadBalancer
  ports:
    - port: 12321
      protocol: TCP
      targetPort: 12321
